### ISSUE TITLE
A little trouble ...

### ISSUE THREAD

**Issue by RJP43** [RJP43/OneWordHistory_CHEAP#2]
@ebeshero @ghbondar @nlottig94 @djbpitt 

Any help would be much appreciated!

I am attempting to transform my Sample Data XML files into HTML using XSLT but for some reason I am not getting the results I want. 
I got `<xsl:for-each>` to work for my [definitions](https://github.com/RJP43/OneWordHistory_CHEAP/tree/master/OED), but now when I am applying a similar XSLT to my samples data it isn't working. I am guessing it is a little path step error, but I am not seeing it. You can find the [source XML here](https://github.com/RJP43/OneWordHistory_CHEAP/blob/master/EANO/EANO_sample1915.xml) and my [XSLT here](https://github.com/RJP43/OneWordHistory_CHEAP/blob/master/EANO/EANO_sample1915.xsl). Once I get this first one correct I can use it to format the rest of my sample data XML documents because they are all similarly coded. 

Thanks in advance!

**Comment by RJP43** [comment]
Never-mind I figured it out!

**Comment by ebeshero** [comment]
Yay! Glad you worked it out, Becca! :+1:
