### ISSUE TITLE
Issue getting Dates on Timeline Graph

### ISSUE THREAD

**Issue by RJP43** [RJP43/OneWordHistory_CHEAP#3]
@ebeshero
 Okay so now I have a different problem I am hoping you can help me with ... I am trying to run [this XSLT](https://github.com/RJP43/OneWordHistory_CHEAP/blob/master/dataVis/timeLineGraph.xsl) over this [collection of sample XML files](https://github.com/RJP43/OneWordHistory_CHEAP/tree/master/dataVis/samples) to create a timeline graph that shows the frequency of different parts of speech that appeared within my samples.

I plan to have the Parts of Speech each be represented by different line colors (likely by making them appear within the same space using Javascript toggling (similar to the original Nelson bar graph)).

However,  I am having a very basic issue getting the dates to work along the bottom of the graph ([see my output here](https://github.com/RJP43/OneWordHistory_CHEAP/blob/master/dataVis/output)). It seems to be grabbing all of the dates in all of the files individually and not giving me the distinct values  like I was trying to do. Let me know if you need further explanation. Much appreciated!

my inspiiration for this kind of data visualization comes from [Google N Gram](https://books.google.com/ngrams)

**Comment by RJP43** [comment]
@ebeshero if you get time to look at all of the things we have attempted it would be much appreciated... if not that is fine too... either way I do appreciate all your help earlier and I am sorry I was so cranky earlier. It has been a rough week.

**Comment by ebeshero** [comment]
@RJP43 I think we resolved this, right?

**Comment by RJP43** [comment]
no not entirely .. @nlottig94  and I drew the graph by hand ... however I think I can figure this out especially with all the new SVG experience I got working with Spadafore. I'm going to close this issue and edit this project some time before graduation. I'm opening a new issue with a to do list. Thanks!
